script:
  - ./bin/hugo

deploy:
  local_dir: public # Default static site output dir for Hugo
  repo: Informasjonsforvaltning/Informasjonsforvaltning.github.io # This is the slug of the repo you want to deploy your site to
  target_branch: master # GitHub pages branch to deploy to (in other cases it can be gh-pages)
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # This is the authentication which you will setup in the next step in travis-ci dashboard
  email: stigbd@gmail.com
  name: "Stig B. Dørmænen"
  on:
    branch: master

notifications:
    slack: br-inforvalt:JCeNMCKAXjtRbvbNeFTrtwX3
